server:
  address: 0.0.0.0
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 8192
    accept-count: 100
    uri-encoding: UTF-8
    max-http-form-post-size: 2MB
    max-swallow-size: 2MB
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 1MB
      max-request-size: 10MB

